const $a=(s,c=document)=>c.querySelector(s);
const TARIFF_KEY='energyguard_tariff_v1';
const DEFAULT_TARIFF=2204.0655;
function n(v){const x=Number(v);return Number.isFinite(x)?x:0}
function f(v,d=2){return n(v).toLocaleString('vi-VN',{maximumFractionDigits:d})}
function money(v){return Math.round(n(v)).toLocaleString('vi-VN')+' đ'}
function tariff(){return Math.max(0,n(localStorage.getItem(TARIFF_KEY)||DEFAULT_TARIFF))}
function saveTariff(v){localStorage.setItem(TARIFF_KEY,String(Math.max(0,n(v))))}
function dayKey(run){const raw=run.forecastStartedAt||run.createdAt||'';return String(raw).slice(0,10)}
function latestPerDay(runs){const map=new Map();for(const r of runs){const k=dayKey(r);if(!k)continue;const prev=map.get(k);const rt=new Date(r.createdAt||r.forecastStartedAt||0).getTime();const pt=prev?new Date(prev.createdAt||prev.forecastStartedAt||0).getTime():-1;if(!prev||rt>=pt)map.set(k,r)}return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,run])=>({date,run}))}
function calc(run,price){const s=run.summary||{};const load=n(s.loadKwh);const grid=n(s.gridImportKwh);const solar=n(s.solarKwh);const exp=n(s.gridExportKwh);const avoided=Math.max(0,load-grid);return{load,grid,solar,exportKwh:exp,coverage:n(s.solarCoveragePct),baselineCost:load*price,gridCost:grid*price,avoidedKwh:avoided,savings:avoided*price}}
function setupCanvas(canvas){const rect=canvas.getBoundingClientRect();const ratio=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w:rect.width,h:rect.height}}
function drawChart(days,price){const c=$a('#analytics-chart');if(!c)return;const {ctx,w,h}=setupCanvas(c);ctx.clearRect(0,0,w,h);const pad={l:52,r:58,t:20,b:36};const rows=days.slice(-30).map(x=>({date:x.date,...calc(x.run,price)}));if(!rows.length){ctx.fillStyle='#82968b';ctx.font='14px Inter';ctx.fillText('Chưa có dữ liệu forecast.',24,44);return}const maxGrid=Math.max(1,...rows.map(r=>r.grid))*1.15;const maxSave=Math.max(1,...rows.map(r=>r.savings))*1.15;ctx.font='10px Inter';ctx.strokeStyle='rgba(255,255,255,.07)';ctx.fillStyle='#6f877a';for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(f(maxGrid*(1-i/4),1),4,y+3)}const x=i=>pad.l+(w-pad.l-pad.r)*(i/(rows.length-1||1));const yg=v=>pad.t+(1-v/maxGrid)*(h-pad.t-pad.b);const ys=v=>pad.t+(1-v/maxSave)*(h-pad.t-pad.b);const every=Math.max(1,Math.ceil(rows.length/6));rows.forEach((r,i)=>{if(i%every===0||i===rows.length-1)ctx.fillText(r.date.slice(5),x(i)-14,h-10)});ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(x(i),yg(r.grid)):ctx.moveTo(x(i),yg(r.grid)));ctx.strokeStyle='#ffb45c';ctx.lineWidth=2.4;ctx.stroke();ctx.beginPath();rows.forEach((r,i)=>i?ctx.lineTo(x(i),ys(r.savings)):ctx.moveTo(x(i),ys(r.savings)));ctx.strokeStyle='#b9ff66';ctx.lineWidth=2.4;ctx.stroke();ctx.fillStyle='#6f877a';ctx.textAlign='right';ctx.fillText(money(maxSave),w-4,pad.t+4);ctx.fillText('0 đ',w-4,h-pad.b+3);ctx.textAlign='left'}
function exportCsv(days,price,sys){const rows=[['date','system','load_kwh','solar_kwh','grid_import_kwh','grid_export_kwh','solar_coverage_pct','reference_tariff_vnd_kwh','grid_cost_vnd','estimated_savings_vnd']];for(const d of days){const x=calc(d.run,price);rows.push([d.date,sys.name,x.load,x.solar,x.grid,x.exportKwh,x.coverage,price,Math.round(x.gridCost),Math.round(x.savings)])}const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`energyguard-analytics-${sys.name.replace(/[^a-zA-Z0-9_-]+/g,'-')}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function render(){const sys=EnergyGuardAuth.loadSystem();const out=await EnergyGuardAuth.getForecastHistory();const runs=(out.runs||[]).filter(r=>!r.systemId||r.systemId===sys.id);const days=latestPerDay(runs);const price=tariff();$a('#tariff').value=price;$a('#analytics-sub').textContent=`${sys.name} · ${sys.solarKwp} kWp solar · ${sys.batteryKwh} kWh battery · ${days.length} ngày forecast`;const totals=days.reduce((acc,d)=>{const x=calc(d.run,price);Object.keys(acc).forEach(k=>acc[k]+=x[k]||0);return acc},{load:0,grid:0,solar:0,exportKwh:0,coverage:0,baselineCost:0,gridCost:0,avoidedKwh:0,savings:0});const selfPct=totals.load>0?totals.avoidedKwh/totals.load*100:0;$a('#a-load').textContent=f(totals.load)+' kWh';$a('#a-days').textContent=`${days.length} ngày dữ liệu`;$a('#a-grid').textContent=f(totals.grid)+' kWh';$a('#a-grid-cost').textContent=money(totals.gridCost);$a('#a-solar-used').textContent=f(totals.avoidedKwh)+' kWh';$a('#a-self').textContent=f(selfPct,1)+'% tự chủ';$a('#a-savings').textContent=money(totals.savings);$a('#a-savings-kwh').textContent=f(totals.avoidedKwh)+' kWh giảm mua lưới';$a('#sum-system').textContent=sys.name;$a('#sum-solar').textContent=f(sys.solarKwp,1)+' kWp';$a('#sum-battery').textContent=f(sys.batteryKwh,1)+' kWh';$a('#sum-ev').textContent=f(sys.evBatteryKwh,1)+' kWh';const latest=runs[0];$a('#sum-last').textContent=latest?new Date(latest.createdAt||latest.forecastStartedAt).toLocaleString('vi-VN'):'—';$a('#sum-model').textContent=latest?.modelName||'—';const body=$a('#analytics-body');body.innerHTML='';if(!days.length){body.innerHTML='<tr><td colspan="8">Chưa có forecast. Hãy vào Lịch sử và ghi forecast mới.</td></tr>'}else{for(const d of [...days].reverse()){const x=calc(d.run,price);const tr=document.createElement('tr');tr.innerHTML=`<td>${d.date}</td><td>${f(x.load)} kWh</td><td>${f(x.solar)} kWh</td><td>${f(x.grid)} kWh</td><td>${f(x.exportKwh)} kWh</td><td>${f(x.coverage,1)}%</td><td>${money(x.gridCost)}</td><td><strong>${money(x.savings)}</strong></td>`;body.appendChild(tr)}}drawChart(days,price);$a('#export-csv').onclick=()=>exportCsv(days,price,sys)}
$a('#save-tariff')?.addEventListener('click',()=>{saveTariff($a('#tariff').value);render()});window.addEventListener('resize',()=>render());render();
