const AUTH_BASE='https://energyguard-auth.onrender.com';
const SESSION_KEY='energyguard_session_v1';
const USER_KEY='energyguard_user_v1';
const LEGACY_SYSTEM_KEY='energyguard_system_v1';
const SYSTEMS_KEY='energyguard_systems_v2';
const ACTIVE_SYSTEM_KEY='energyguard_active_system_v2';
const HISTORY_KEY='energyguard_forecast_history_v1';
let supabaseClient=null;

async function authFetch(path,options={}){const r=await fetch(AUTH_BASE+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function getSession(){return localStorage.getItem(SESSION_KEY)||''}
function getUser(){try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}}
function setSession(token,user){localStorage.setItem(SESSION_KEY,token);localStorage.setItem(USER_KEY,JSON.stringify(user))}
function clearSession(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem(USER_KEY)}
async function getMe(){const token=getSession();if(!token)return null;try{return await authFetch('/me',{headers:{Authorization:`Bearer ${token}`}})}catch{clearSession();return null}}
function uid(){return crypto.randomUUID?crypto.randomUUID():`eg-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function defaultSystem(){return{id:uid(),name:'Hệ thống chính',lat:21.0285,lon:105.8542,dailyConsumptionKwh:20,solarKwp:5,batteryKwh:10,initialSocPct:60,evBatteryKwh:60,evTargetPct:80}}
function migrateLegacy(){try{const existing=JSON.parse(localStorage.getItem(SYSTEMS_KEY)||'null');if(Array.isArray(existing)&&existing.length)return existing;const old=JSON.parse(localStorage.getItem(LEGACY_SYSTEM_KEY)||'null');const first={...defaultSystem(),...(old||{})};localStorage.setItem(SYSTEMS_KEY,JSON.stringify([first]));localStorage.setItem(ACTIVE_SYSTEM_KEY,first.id);localStorage.setItem(LEGACY_SYSTEM_KEY,JSON.stringify(first));return[first]}catch{const d=defaultSystem();return[d]}}
function getSystems(){try{const arr=JSON.parse(localStorage.getItem(SYSTEMS_KEY)||'null');return Array.isArray(arr)&&arr.length?arr:migrateLegacy()}catch{return migrateLegacy()}}
function saveSystems(list){localStorage.setItem(SYSTEMS_KEY,JSON.stringify(list.slice(0,20)))}
function getActiveSystem(){const list=getSystems();const id=localStorage.getItem(ACTIVE_SYSTEM_KEY);const found=list.find(x=>x.id===id)||list[0];if(found){localStorage.setItem(ACTIVE_SYSTEM_KEY,found.id);localStorage.setItem(LEGACY_SYSTEM_KEY,JSON.stringify(found))}return found||defaultSystem()}
function setActiveSystem(id){const list=getSystems();const found=list.find(x=>x.id===id);if(found){localStorage.setItem(ACTIVE_SYSTEM_KEY,found.id);localStorage.setItem(LEGACY_SYSTEM_KEY,JSON.stringify(found));localStorage.setItem('energyguard-dashboard-config',JSON.stringify({lat:found.lat,lon:found.lon,dailyLoad:found.dailyConsumptionKwh,solarKwp:found.solarKwp,batteryKwh:found.batteryKwh,soc:found.initialSocPct}))}return found}
function saveSystem(v){const list=getSystems();const id=v.id||localStorage.getItem(ACTIVE_SYSTEM_KEY)||uid();const item={...defaultSystem(),...v,id,name:String(v.name||'Hệ thống').trim()||'Hệ thống'};const idx=list.findIndex(x=>x.id===id);if(idx>=0)list[idx]=item;else list.push(item);saveSystems(list);setActiveSystem(id);return item}
function deleteSystem(id){let list=getSystems().filter(x=>x.id!==id);if(!list.length)list=[defaultSystem()];saveSystems(list);setActiveSystem(list[0].id);return list}
function loadSystem(){return getActiveSystem()}
function localHistory(){try{const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(h)?h:[]}catch{return[]}}
function addLocalHistory(run){const next=[{id:run.id||uid(),createdAt:run.createdAt||new Date().toISOString(),...run},...localHistory()].slice(0,100);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));return next[0]}
function clearLocalHistory(){localStorage.removeItem(HISTORY_KEY)}
async function authed(path,options={}){const token=getSession();if(!token)throw new Error('Chưa đăng nhập');return authFetch(path,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}})}
async function storageStatus(){try{return await authFetch('/storage/status')}catch{return{persistent:false,mode:'offline'}}}
async function syncSystem(item){if(!getSession())return null;try{return await authed('/systems',{method:'POST',body:JSON.stringify(item)})}catch{return null}}
async function pushForecastRun(run){addLocalHistory(run);if(!getSession())return{local:true};try{return await authed('/forecast-runs',{method:'POST',body:JSON.stringify(run)})}catch{return{local:true}}}
async function getForecastHistory(){const local=localHistory();if(!getSession())return{runs:local,persistent:false,source:'local'};try{const remote=await authed('/forecast-runs?limit=100');const map=new Map();[...remote.runs,...local].forEach(x=>map.set(x.id||`${x.createdAt}-${x.systemId}`,x));return{runs:[...map.values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),persistent:Boolean(remote.persistent),source:remote.persistent?'database':'server-memory + local'}}catch{return{runs:local,persistent:false,source:'local'}}}
function loginNext(){const raw=new URLSearchParams(location.search).get('next')||'dashboard.html';const allowed=new Set(['dashboard.html','account.html','history.html','analytics.html','index.html']);return allowed.has(raw)?raw:'dashboard.html'}
function setStatus(text,type=''){const el=document.querySelector('#login-status');if(!el)return;el.textContent=text;el.className='status'+(type?` ${type}`:'')}
function friendlyAuthError(err){const m=String(err?.message||err||'Đã có lỗi xảy ra.');if(/invalid login credentials/i.test(m))return'Email hoặc mật khẩu không đúng.';if(/email not confirmed/i.test(m))return'Email chưa được xác minh. Hãy mở email xác nhận từ EnergyGuard.';if(/user already registered/i.test(m))return'Email này đã có tài khoản. Hãy chọn Đăng nhập.';if(/password/i.test(m)&&/least|characters|short/i.test(m))return'Mật khẩu chưa đủ mạnh. Hãy dùng ít nhất 8 ký tự.';return m}
async function waitForSupabaseLibrary(timeout=8000){const start=Date.now();while(Date.now()-start<timeout){if(window.supabase?.createClient)return window.supabase;await new Promise(r=>setTimeout(r,80))}throw new Error('Không tải được thư viện Supabase Auth.')}
async function createSupabaseClient(cfg){if(supabaseClient)return supabaseClient;if(!cfg?.supabaseEnabled||!cfg.supabaseUrl||!cfg.supabasePublishableKey)throw new Error('Supabase Auth chưa được cấu hình.');const lib=await waitForSupabaseLibrary();supabaseClient=lib.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return supabaseClient}
async function exchangeSupabaseSession(session,next){if(!session?.access_token)throw new Error('Supabase không trả về access token.');const out=await authFetch('/supabase/session',{method:'POST',body:JSON.stringify({accessToken:session.access_token})});setSession(out.sessionToken,out.user);try{await supabaseClient?.auth.signOut({scope:'local'})}catch{}setStatus('Đăng nhập thành công. Đang mở EnergyGuard…','ok');setTimeout(()=>location.href=next,300)}

async function initLogin(){
  const next=loginNext();const shell=document.querySelector('#google-button');const guest=document.querySelector('#guest-btn');const help=document.querySelector('#oauth-help');const form=document.querySelector('#email-auth-form');const email=document.querySelector('#auth-email');const password=document.querySelector('#auth-password');const submit=document.querySelector('#email-submit');const switchMode=document.querySelector('#switch-auth-mode');const title=document.querySelector('#auth-title');const subtitle=document.querySelector('#auth-subtitle');const forgotBtn=document.querySelector('#forgot-password-btn');const forgotForm=document.querySelector('#forgot-form');const forgotEmail=document.querySelector('#forgot-email');const cancelForgot=document.querySelector('#cancel-forgot');let mode='signin';
  if(getSession()){const me=await getMe();if(me?.ok){location.href=next;return}}
  guest?.addEventListener('click',()=>location.href='dashboard.html');
  document.querySelector('#toggle-password')?.addEventListener('click',e=>{const show=password.type==='password';password.type=show?'text':'password';e.currentTarget.textContent=show?'Ẩn':'Hiện'});
  document.querySelectorAll('[data-login-method]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-login-method]').forEach(x=>x.classList.toggle('active',x===btn));const phone=btn.dataset.loginMethod==='phone';document.querySelector('#email-auth-panel').hidden=phone;document.querySelector('#phone-auth-panel').hidden=!phone;setStatus(phone?'Đăng nhập SMS OTP chưa được kích hoạt. Email + mật khẩu đang hoạt động.':'Email + mật khẩu sẵn sàng.','')}));
  function applyMode(){const signup=mode==='signup';title.textContent=signup?'Tạo tài khoản EnergyGuard':'Đăng nhập EnergyGuard';subtitle.textContent=signup?'Đăng ký bằng email. Bạn sẽ cần xác minh email trước khi đăng nhập.':'Đăng nhập bằng email và mật khẩu của bạn.';submit.textContent=signup?'Tạo tài khoản':'Đăng nhập';switchMode.textContent=signup?'Tôi đã có tài khoản':'Tạo tài khoản mới';password.autocomplete=signup?'new-password':'current-password';forgotBtn.hidden=signup}
  switchMode?.addEventListener('click',()=>{mode=mode==='signin'?'signup':'signin';forgotForm.hidden=true;form.hidden=false;applyMode();setStatus(mode==='signup'?'Nhập email và mật khẩu để tạo tài khoản mới.':'Email + mật khẩu sẵn sàng.','')});
  forgotBtn?.addEventListener('click',()=>{forgotEmail.value=email.value;form.hidden=true;forgotForm.hidden=false;setStatus('Nhập email để nhận liên kết đặt lại mật khẩu.','')});
  cancelForgot?.addEventListener('click',()=>{forgotForm.hidden=true;form.hidden=false;setStatus('Email + mật khẩu sẵn sàng.','')});
  applyMode();
  try{
    const cfg=await authFetch('/config');const sb=await createSupabaseClient(cfg);
    if(new URLSearchParams(location.search).get('confirmed')==='1')setStatus('Email đã được xác minh. Đang hoàn tất đăng nhập…','ok');else setStatus('Email + mật khẩu sẵn sàng.','ok');
    const {data:{session}}=await sb.auth.getSession();if(session){await exchangeSupabaseSession(session,next);return}
    form?.addEventListener('submit',async e=>{e.preventDefault();const em=email.value.trim();const pw=password.value;if(!em||!pw){setStatus('Vui lòng nhập đầy đủ email và mật khẩu.','warn');return}if(pw.length<8){setStatus('Mật khẩu cần ít nhất 8 ký tự.','warn');return}submit.disabled=true;const old=submit.textContent;submit.textContent=mode==='signup'?'Đang tạo tài khoản…':'Đang đăng nhập…';try{if(mode==='signup'){const {data,error}=await sb.auth.signUp({email:em,password:pw,options:{emailRedirectTo:`${location.origin}/login.html?next=${encodeURIComponent(next)}&confirmed=1`}});if(error)throw error;if(data.session){await exchangeSupabaseSession(data.session,next);return}setStatus('Đã tạo tài khoản. Hãy mở email xác nhận từ Supabase/EnergyGuard rồi quay lại đăng nhập.','ok');password.value='';mode='signin';applyMode()}else{const {data,error}=await sb.auth.signInWithPassword({email:em,password:pw});if(error)throw error;await exchangeSupabaseSession(data.session,next)}}catch(err){setStatus(friendlyAuthError(err),'warn')}finally{submit.disabled=false;submit.textContent=old;if(mode==='signin')submit.textContent='Đăng nhập'}});
    forgotForm?.addEventListener('submit',async e=>{e.preventDefault();const em=forgotEmail.value.trim();if(!em){setStatus('Vui lòng nhập email.','warn');return}const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{const {error}=await sb.auth.resetPasswordForEmail(em,{redirectTo:`${location.origin}/reset-password.html`});if(error)throw error;setStatus('Nếu email tồn tại, EnergyGuard đã gửi liên kết đặt lại mật khẩu.','ok')}catch(err){setStatus(friendlyAuthError(err),'warn')}finally{btn.disabled=false}});
    if(!cfg.googleEnabled||!cfg.googleClientId){help.hidden=false;shell.innerHTML='<button class="google-placeholder" disabled><span class="google-g">G</span><span>Tiếp tục với Google</span><small>Chưa kích hoạt</small></button>'}else{help.hidden=true;const boot=()=>{if(!window.google?.accounts?.id)return setTimeout(boot,150);google.accounts.id.initialize({client_id:cfg.googleClientId,callback:async resp=>{try{setStatus('Đang xác minh tài khoản Google…');const out=await authFetch('/google',{method:'POST',body:JSON.stringify({credential:resp.credential})});setSession(out.sessionToken,out.user);setStatus('Đăng nhập thành công.','ok');setTimeout(()=>location.href=next,300)}catch(err){setStatus(friendlyAuthError(err),'warn')}},use_fedcm_for_prompt:true});shell.innerHTML='';google.accounts.id.renderButton(shell,{theme:'filled_black',size:'large',shape:'pill',text:'continue_with',width:330})};boot()}
  }catch(err){setStatus('Dịch vụ đăng nhập chưa sẵn sàng: '+friendlyAuthError(err),'warn')}
}

async function initResetPassword(){
  const status=document.querySelector('#reset-status');const form=document.querySelector('#reset-form');const p1=document.querySelector('#new-password');const p2=document.querySelector('#confirm-password');
  try{const cfg=await authFetch('/config');const sb=await createSupabaseClient(cfg);const {data:{session}}=await sb.auth.getSession();if(!session){status.textContent='Liên kết đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.';status.className='status warn';form.hidden=true;return}status.textContent='Bạn có thể đặt mật khẩu mới.';status.className='status ok';form.addEventListener('submit',async e=>{e.preventDefault();if(p1.value.length<8){status.textContent='Mật khẩu cần ít nhất 8 ký tự.';status.className='status warn';return}if(p1.value!==p2.value){status.textContent='Hai mật khẩu chưa khớp.';status.className='status warn';return}const btn=form.querySelector('button[type="submit"]');btn.disabled=true;try{const {error}=await sb.auth.updateUser({password:p1.value});if(error)throw error;await sb.auth.signOut({scope:'local'});status.textContent='Đổi mật khẩu thành công. Đang quay lại đăng nhập…';status.className='status ok';setTimeout(()=>location.href='login.html',900)}catch(err){status.textContent=friendlyAuthError(err);status.className='status warn'}finally{btn.disabled=false}})}catch(err){status.textContent='Không thể mở phiên đặt lại mật khẩu: '+friendlyAuthError(err);status.className='status warn';form.hidden=true}
}

function fillSystemForm(sys){for(const [k,v] of Object.entries(sys||{})){const el=document.querySelector(`[name="${k}"]`);if(el)el.value=v??''}}
function renderSystems(){const wrap=document.querySelector('#systems-list');if(!wrap)return;const active=getActiveSystem();wrap.innerHTML='';getSystems().forEach(sys=>{const el=document.createElement('article');el.className='system-item'+(sys.id===active.id?' active':'');el.innerHTML=`<div><strong>${sys.name}</strong><small>${sys.solarKwp} kWp solar · ${sys.batteryKwh} kWh battery · ${sys.dailyConsumptionKwh} kWh/day</small></div><div class="system-actions"><button data-open="${sys.id}">Mở</button><button data-delete="${sys.id}" class="danger">Xóa</button></div>`;wrap.appendChild(el)});wrap.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{setActiveSystem(b.dataset.open);fillSystemForm(getActiveSystem());renderSystems()});wrap.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(getSystems().length<=1)return;deleteSystem(b.dataset.delete);fillSystemForm(getActiveSystem());renderSystems()})}
async function initAccount(){const me=await getMe();if(!me?.ok){location.href='login.html?next=account.html';return}const u=me.user;document.querySelector('#profile-name').textContent=u.name||'EnergyGuard User';document.querySelector('#profile-email').textContent=u.email||'';document.querySelector('#profile-sub').textContent=u.sub||'';document.querySelector('#profile-exp').textContent=new Date(me.expiresAt).toLocaleString('vi-VN');const avatar=document.querySelector('#profile-avatar');if(u.picture){avatar.innerHTML=`<img src="${u.picture}" alt="Ảnh đại diện">`}else avatar.textContent=(u.name||'E').slice(0,1).toUpperCase();fillSystemForm(getActiveSystem());renderSystems();const st=await storageStatus();const storage=document.querySelector('#storage-state');if(storage){storage.textContent=st.persistent?'PostgreSQL persistence đang hoạt động.':'Chế độ fallback cục bộ/server-memory; Postgres chưa được gắn DATABASE_URL.';storage.className='status '+(st.persistent?'ok':'warn')}document.querySelector('#new-system-btn')?.addEventListener('click',()=>{const d=defaultSystem();d.name=`Hệ thống ${getSystems().length+1}`;const saved=saveSystem(d);fillSystemForm(saved);renderSystems()});document.querySelector('#system-form')?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const current=getActiveSystem();const next={id:current.id,name:String(fd.get('name')||current.name),lat:Number(fd.get('lat')),lon:Number(fd.get('lon')),dailyConsumptionKwh:Number(fd.get('dailyConsumptionKwh')),solarKwp:Number(fd.get('solarKwp')),batteryKwh:Number(fd.get('batteryKwh')),initialSocPct:Number(fd.get('initialSocPct')),evBatteryKwh:Number(fd.get('evBatteryKwh')),evTargetPct:Number(fd.get('evTargetPct'))};const saved=saveSystem(next);await syncSystem(saved);renderSystems();const msg=document.querySelector('#save-msg');msg.textContent=st.persistent?'Đã lưu và đồng bộ database.':'Đã lưu trên thiết bị; API sync đã nhận cấu trúc nhưng storage server hiện chưa persistent.';msg.className='status '+(st.persistent?'ok':'warn')});document.querySelector('#logout-btn')?.addEventListener('click',async()=>{try{await authed('/logout',{method:'POST'})}catch{}clearSession();location.href='login.html?next=dashboard.html'})}

window.EnergyGuardAuth={getSession,getUser,getMe,loadSystem,saveSystem,getSystems,getActiveSystem,setActiveSystem,deleteSystem,pushForecastRun,getForecastHistory,addLocalHistory,clearLocalHistory,storageStatus,authed};
if(document.body.dataset.page==='login')initLogin();
if(document.body.dataset.page==='account')initAccount();
if(document.body.dataset.page==='reset-password')initResetPassword();
