const API_BASE='https://energyguard-api.onrender.com';
const ML_BASE='https://energyguard-model.onrender.com';
const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const state={config:null,weather:null,labels:[],rows:[],load:[],solar:[],optimization:null,benchmark:null,modelMeta:null,modelName:'',advisor:null,filter:'all'};

function clamp(v,min,max){return Math.min(max,Math.max(min,v))}
function fmt(v,d=2){return Number(v??0).toLocaleString('vi-VN',{minimumFractionDigits:0,maximumFractionDigits:d})}
function titleCase(s){return String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function jsonFetch(url,options={},timeout=30000){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...options,signal:ctl.signal,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}finally{clearTimeout(timer)}}
const api=(path,options={})=>jsonFetch(API_BASE+path,options,22000);const ml=(path,options={})=>jsonFetch(ML_BASE+path,options,45000);
function showLoading(title='Đang cập nhật EnergyGuard',sub='Weather → ML → Battery optimizer'){const el=$('#loading-overlay');$('#loading-title').textContent=title;$('#loading-subtitle').textContent=sub;el.classList.remove('hidden')}
function hideLoading(){$('#loading-overlay').classList.add('hidden')}
let toastTimer;function toast(title,sub){const el=$('#toast');$('strong',el).textContent=title;$('span',el).textContent=sub;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
function estimatePv(ghi,temp,kwp){const irr=clamp(Number(ghi||0)/1000,0,1.25);const tempPenalty=Number(temp)>25?clamp(1-(Number(temp)-25)*.004,.82,1):1;return Math.round(kwp*irr*.82*tempPenalty*1000)/1000}
function readConfig(){const cfg={lat:clamp(Number($('#lat').value)||21.0285,-90,90),lon:clamp(Number($('#lon').value)||105.8542,-180,180),dailyLoad:clamp(Number($('#daily-load').value)||20,1,100000),solarKwp:clamp(Number($('#solar-kwp').value)||5,.1,5000),batteryKwh:clamp(Number($('#battery-kwh').value)||10,.5,10000),soc:clamp(Number($('#soc').value)||60,15,95)};localStorage.setItem('energyguard-dashboard-config',JSON.stringify(cfg));return cfg}
function restoreConfig(){try{const cfg=JSON.parse(localStorage.getItem('energyguard-dashboard-config')||'null');if(!cfg)return;[['lat',cfg.lat],['lon',cfg.lon],['daily-load',cfg.dailyLoad],['solar-kwp',cfg.solarKwp],['battery-kwh',cfg.batteryKwh],['soc',cfg.soc]].forEach(([id,v])=>{if(v!=null)$(`#${id}`).value=v})}catch{}}

async function getWeather(cfg){try{const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',cfg.lat);u.searchParams.set('longitude',cfg.lon);u.searchParams.set('forecast_days','2');u.searchParams.set('timezone','auto');u.searchParams.set('current','temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_10m');u.searchParams.set('hourly','temperature_2m,relative_humidity_2m,cloud_cover,precipitation,shortwave_radiation,direct_normal_irradiance,diffuse_radiation,wind_speed_10m');const r=await fetch(u);if(!r.ok)throw new Error(`Open-Meteo HTTP ${r.status}`);const d=await r.json();const h=d.hourly||{};return{source:'Open-Meteo direct',timezone:d.timezone,current:d.current||{},hourly:{time:h.time||[],temperatureC:h.temperature_2m||[],humidityPct:h.relative_humidity_2m||[],cloudCoverPct:h.cloud_cover||[],precipitationMm:h.precipitation||[],ghiWm2:h.shortwave_radiation||[],diffuseWm2:h.diffuse_radiation||[],windSpeedKmh:h.wind_speed_10m||[],estimatedSolarKw:(h.time||[]).map((_,i)=>estimatePv(h.shortwave_radiation?.[i],h.temperature_2m?.[i],cfg.solarKwp))}}}catch(err){console.warn('Direct weather failed, trying proxy',err);return api(`/api/weather?lat=${cfg.lat}&lon=${cfg.lon}&days=2&capacity_kwp=${cfg.solarKwp}`)}}
function currentIndex(times,current){const key=String(current||'').slice(0,13);let idx=times.findIndex(t=>String(t).slice(0,13)===key);if(idx<0)idx=times.findIndex(t=>String(t).slice(0,13)>key);return idx<0?0:idx}
function makeRows(weather,start){const h=weather.hourly||{};return(h.time||[]).slice(start,start+24).map((t,i)=>{const j=start+i;return{hour:Number(String(t).slice(11,13)),weekday:new Date(String(t).slice(0,10)+'T12:00:00').getDay(),month:Number(String(t).slice(5,7)),temperatureC:h.temperatureC?.[j],humidityPct:h.humidityPct?.[j],windSpeedKmh:h.windSpeedKmh?.[j]??weather.current?.wind_speed_10m,ghiWm2:h.ghiWm2?.[j],diffuseWm2:h.diffuseWm2?.[j]}})}
async function predictLoad(cfg,rows){try{const out=await ml('/predict',{method:'POST',body:JSON.stringify({baseLoadKw:cfg.dailyLoad/24,hours:rows})});return{...out,fallback:false}}catch(err){console.warn('ML unavailable, fallback baseline',err);const out=await api('/api/predict/load',{method:'POST',body:JSON.stringify({baseLoadKw:cfg.dailyLoad/24,hours:rows})});return{...out,fallback:true}}}
async function fetchMetrics(){try{return await ml('/metrics')}catch(err){console.warn('Metrics unavailable',err);return null}}
async function optimize(cfg,solar,load){return api('/api/optimize/bess',{method:'POST',body:JSON.stringify({solarKw:solar,loadKw:load,batteryCapacityKwh:cfg.batteryKwh,initialSocPct:cfg.soc,minSocPct:15,maxSocPct:95,maxChargeKw:Math.min(5,cfg.batteryKwh),maxDischargeKw:Math.min(5,cfg.batteryKwh),roundTripEfficiency:.90})})}
async function getAdvisor(solar,load,soc){try{return await api('/api/advisor',{method:'POST',body:JSON.stringify({solarKw:solar,loadKw:load,initialSocPct:soc})})}catch{return{recommendations:[{priority:'normal',title:'Advisor tạm thời không khả dụng',message:'Forecast và battery optimizer vẫn hoạt động. Hãy thử phân tích lại sau.'}]}}}

function setupCanvas(canvas){const rect=canvas.getBoundingClientRect();const ratio=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*ratio);canvas.height=Math.round(rect.height*ratio);const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w:rect.width,h:rect.height}}
function chartBase(ctx,w,h,min,max,labels,zeroLine=false){const pad={l:42,r:16,t:14,b:30};ctx.clearRect(0,0,w,h);ctx.font='10px DM Sans';ctx.fillStyle='#789086';ctx.strokeStyle='rgba(255,255,255,.07)';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const val=max-(max-min)*i/4;ctx.fillText(fmt(val,1),4,y+3)}const every=Math.max(1,Math.ceil(labels.length/6));labels.forEach((lab,i)=>{if(i%every!==0&&i!==labels.length-1)return;const x=pad.l+(w-pad.l-pad.r)*(i/(labels.length-1||1));ctx.fillText(lab,x-10,h-8)});if(zeroLine&&min<0&&max>0){const y=pad.t+(max/(max-min))*(h-pad.t-pad.b);ctx.strokeStyle='rgba(255,255,255,.2)';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}return pad}
function drawLineSeries(ctx,w,h,pad,values,min,max,color,fill){if(!values.length)return;const x=i=>pad.l+(w-pad.l-pad.r)*(i/(values.length-1||1));const y=v=>pad.t+(max-v)/(max-min||1)*(h-pad.t-pad.b);ctx.beginPath();values.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.strokeStyle=color;ctx.lineWidth=2.3;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();if(fill){ctx.lineTo(x(values.length-1),h-pad.b);ctx.lineTo(x(0),h-pad.b);ctx.closePath();ctx.fillStyle=fill;ctx.fill()}}
function drawEnergy(){if(!state.load.length)return;const {ctx,w,h}=setupCanvas($('#energy-canvas'));const vals=[...state.solar,...state.load];const max=Math.max(1,...vals)*1.15;const labels=state.labels.map(v=>v.slice(11,16));const pad=chartBase(ctx,w,h,0,max,labels);drawLineSeries(ctx,w,h,pad,state.solar,0,max,'#c8ff62','rgba(200,255,98,.06)');drawLineSeries(ctx,w,h,pad,state.load,0,max,'#6fb6ff','rgba(111,182,255,.035)')}
function drawSoc(){const soc=state.optimization?.schedule?.map(x=>x.socPct)||[];if(!soc.length)return;const {ctx,w,h}=setupCanvas($('#soc-canvas'));const labels=state.labels.map(v=>v.slice(11,16));const pad=chartBase(ctx,w,h,0,100,labels);drawLineSeries(ctx,w,h,pad,soc,0,100,'#a98cff','rgba(169,140,255,.07)')}
function drawGrid(){const sch=state.optimization?.schedule||[];if(!sch.length)return;const values=sch.map(x=>(x.gridImportKw||0)-(x.gridExportKw||0));const lim=Math.max(1,...values.map(v=>Math.abs(v)))*1.18;const {ctx,w,h}=setupCanvas($('#grid-canvas'));const labels=state.labels.map(v=>v.slice(11,16));const pad=chartBase(ctx,w,h,-lim,lim,labels,true);const zeroY=pad.t+(lim/(2*lim))*(h-pad.t-pad.b);const bw=Math.max(3,(w-pad.l-pad.r)/values.length*.55);values.forEach((v,i)=>{const x=pad.l+(w-pad.l-pad.r)*(i/(values.length-1||1));const y=pad.t+(lim-v)/(2*lim)*(h-pad.t-pad.b);ctx.fillStyle=v>=0?'rgba(255,180,92,.8)':'rgba(200,255,98,.72)';ctx.fillRect(x-bw/2,Math.min(y,zeroY),bw,Math.max(1,Math.abs(zeroY-y)))})}
function drawCharts(){drawEnergy();drawSoc();drawGrid()}

function renderOverview(loadResp){const sch=state.optimization.schedule||[];const now=sch[0]||{};$('#kpi-solar').textContent=`${fmt(state.solar[0])} kW`;$('#kpi-load').textContent=`${fmt(state.load[0])} kW`;$('#kpi-soc').textContent=`${fmt(now.socPct,1)}%`;$('#kpi-battery-action').textContent=now.chargeKw>0?`Charging +${fmt(now.chargeKw)} kW`:now.dischargeKw>0?`Discharging ${fmt(now.dischargeKw)} kW`:'Holding';const grid=(now.gridImportKw||0)-(now.gridExportKw||0);$('#kpi-grid').textContent=`${fmt(Math.abs(grid))} kW`;$('#kpi-grid-sub').textContent=grid>0?'Importing from grid':grid<0?'Exporting to grid':'Grid neutral';$('#kpi-coverage').textContent=`${fmt(state.optimization.summary.solarCoveragePct,1)}%`;$('#kpi-model').textContent=titleCase(loadResp.algorithm||loadResp.model||'Baseline');$('#kpi-model-sub').textContent=loadResp.fallback?'Transparent fallback active':'Trained model · UCI transfer';$('#source-label').textContent=`${state.weather.source||'Weather'} · ${state.weather.timezone||'local time'}`;const maxLoad=Math.max(...state.load);const li=state.load.indexOf(maxLoad);const maxSolar=Math.max(...state.solar);const si=state.solar.indexOf(maxSolar);$('#peak-load-note').textContent=`Peak load: ${fmt(maxLoad)} kW · ${state.labels[li]?.slice(11,16)||'—'}`;$('#peak-solar-note').textContent=`Peak solar: ${fmt(maxSolar)} kW · ${state.labels[si]?.slice(11,16)||'—'}`;$('#forecast-window').textContent=state.labels.length?`${state.labels[0].replace('T',' ')} → ${state.labels.at(-1).replace('T',' ')}`:'24 giờ tới';const s=state.optimization.summary;$('#final-soc').textContent=`${fmt(s.finalSocPct,1)}%`;$('#charge-kwh').textContent=`${fmt(s.batteryChargeKwh)} kWh`;$('#discharge-kwh').textContent=`${fmt(s.batteryDischargeKwh)} kWh`;$('#grid-import-kwh').textContent=`${fmt(s.gridImportKwh)} kWh`;$('#grid-export-kwh').textContent=`${fmt(s.gridExportKwh)} kWh`;$('#solar-kwh').textContent=`${fmt(s.solarKwh)} kWh`}
function renderMetrics(meta){if(!meta){$('#model-quality').textContent='Metrics unavailable';return}state.modelMeta=meta;const best=meta.bestModel;const win=meta.metrics?.[best]||{};$('#model-quality').textContent=`Selected by ${meta.selectedBy||'holdout MAE'}`;$('#winner-name').textContent=titleCase(best);$('#winner-version').textContent=meta.modelVersion||'trained model';$('#winner-mae').textContent=fmt(win.MAE,4);$('#winner-rmse').textContent=fmt(win.RMSE,4);$('#winner-r2').textContent=fmt(win.R2,4);$('#winner-mape').textContent=`${fmt(win.MAPE_pct,2)}%`;const body=$('#model-table-body');body.innerHTML='';Object.entries(meta.metrics||{}).forEach(([name,m])=>{const tr=document.createElement('tr');if(name===best)tr.className='winner';tr.innerHTML=`<td><strong>${titleCase(name)}</strong>${name===best?' ★':''}</td><td>${fmt(m.MAE,4)}</td><td>${fmt(m.RMSE,4)}</td><td>${fmt(m.R2,4)}</td><td>${fmt(m.MAPE_pct,2)}%</td>`;body.appendChild(tr)});$('#dataset-name').textContent=meta.dataset?.name||'UCI energy dataset';$('#dataset-meta').textContent=`${meta.dataset?.source||'UCI'} · ${meta.dataset?.license||''} · DOI ${meta.dataset?.doi||'—'}`;$('#split-info').textContent=`${meta.split?.trainRows||'—'} / ${meta.split?.testRows||'—'} rows`}
function hourAdvice(step){if(step.chargeKw>.05)return'Tận dụng solar dư để sạc pin';if(step.dischargeKw>.05)return'Dùng pin để giảm điện mua từ lưới';if(step.gridExportKw>.05)return'Solar dư sau khi pin đạt giới hạn';if(step.gridImportKw>.05)return'Đang cần điện lưới';return'Hệ thống cân bằng'}
function rowState(step){if(step.chargeKw>.05)return'charge';if(step.dischargeKw>.05)return'discharge';if(step.gridImportKw>.05||step.gridExportKw>.05)return'grid';return'hold'}
function renderSchedule(){const body=$('#schedule-body');body.innerHTML='';const sch=state.optimization?.schedule||[];sch.forEach((step,i)=>{const st=rowState(step);if(state.filter!=='all'&&state.filter!==st)return;const grid=(step.gridImportKw||0)-(step.gridExportKw||0);const battery=step.chargeKw>.05?`+${fmt(step.chargeKw)} kW`:step.dischargeKw>.05?`−${fmt(step.dischargeKw)} kW`:'0 kW';const tr=document.createElement('tr');tr.dataset.state=st;tr.innerHTML=`<td><strong>${state.labels[i]?.slice(11,16)||i}</strong></td><td>${fmt(state.rows[i]?.temperatureC,1)}°C</td><td>${fmt(step.solarKw)} kW</td><td>${fmt(step.loadKw)} kW</td><td><span class="state-pill ${st}">${battery}</span></td><td>${fmt(step.socPct,1)}%</td><td>${grid>0?`Import ${fmt(grid)}`:grid<0?`Export ${fmt(-grid)}`:'Neutral'} kW</td><td>${hourAdvice(step)}</td>`;body.appendChild(tr)});if(!body.children.length)body.innerHTML='<tr><td colspan="8">Không có mốc giờ phù hợp bộ lọc.</td></tr>'}
function renderAdvisor(data){state.advisor=data;const grid=$('#advisor-grid');grid.innerHTML='';(data?.recommendations||[]).forEach(rec=>{const a=document.createElement('article');a.className=`advisor-card ${rec.priority||'normal'}`;a.innerHTML=`<span class="advisor-priority">${rec.priority||'normal'} priority</span><h3>${rec.title}</h3><p>${rec.message}</p>`;grid.appendChild(a)});if(!grid.children.length)grid.innerHTML='<article class="advisor-card"><h3>Chưa có khuyến nghị</h3><p>Hệ thống chưa phát hiện sự kiện đáng chú ý.</p></article>'}
function updateStatus(ok,loadResp){$('#side-status').textContent=ok?'Services online':'Fallback mode';$('.connection-dot').classList.toggle('ok',ok);$('#live-state').textContent=loadResp?.fallback?'FALLBACK':'LIVE';$('#updated-at').textContent=new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});$('#footer-status').textContent=loadResp?.fallback?'ML fallback active · data transparency enabled':'Random Forest active · data transparency enabled'}

async function runDashboard(){showLoading();const cfg=readConfig();state.config=cfg;try{const metricsPromise=fetchMetrics();$('#loading-subtitle').textContent='Đang lấy weather và solar forecast';const weather=await getWeather(cfg);state.weather=weather;const h=weather.hourly||{};const start=currentIndex(h.time||[],weather.current?.time);state.labels=(h.time||[]).slice(start,start+24);state.rows=makeRows(weather,start);state.solar=(h.estimatedSolarKw||[]).slice(start,start+24);$('#loading-subtitle').textContent='Đang chạy Random Forest load forecast';const loadResp=await predictLoad(cfg,state.rows);state.load=loadResp.forecast.map(x=>x.predictedLoadKw);state.modelName=loadResp.algorithm||loadResp.model;state.benchmark=loadResp.benchmark||null;$('#loading-subtitle').textContent='Đang tối ưu lịch sạc/xả battery';state.optimization=await optimize(cfg,state.solar,state.load);const [advisor,meta]=await Promise.all([getAdvisor(state.solar,state.load,cfg.soc),metricsPromise]);renderOverview(loadResp);renderMetrics(meta);renderSchedule();renderAdvisor(advisor);drawCharts();updateStatus(!loadResp.fallback,loadResp);toast('Forecast đã cập nhật',`${titleCase(state.modelName)} · ${state.labels.length} giờ · Solar + Load + BESS`)}catch(err){console.error(err);updateStatus(false,{fallback:true});toast('Không thể hoàn tất forecast',err.name==='AbortError'?'Service phản hồi quá chậm. Dữ liệu cũ vẫn được giữ.':err.message)}finally{hideLoading()}}

$('#system-form').addEventListener('submit',e=>{e.preventDefault();runDashboard()});$('#refresh-btn').addEventListener('click',runDashboard);$('#advisor-refresh').addEventListener('click',async()=>{if(!state.load.length)return runDashboard();showLoading('Đang phân tích lại Advisor','Đọc Solar · Load · SOC');const data=await getAdvisor(state.solar,state.load,state.config.soc);renderAdvisor(data);hideLoading();toast('Advisor đã cập nhật','Khuyến nghị mới dựa trên forecast hiện tại.')});$$('.table-filter button').forEach(btn=>btn.addEventListener('click',()=>{$$('.table-filter button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderSchedule()}));
const navObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;$$('.side-links a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`))}),{rootMargin:'-20% 0px -65% 0px'});['overview','forecast','battery','model','schedule','advisor'].forEach(id=>{const el=$(`#${id}`);if(el)navObserver.observe(el)});let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawCharts,180)});restoreConfig();runDashboard();