const API_BASE_HISTORY='https://energyguard-api.onrender.com';
const ML_BASE_HISTORY='https://energyguard-model.onrender.com';
const $h=(s,c=document)=>c.querySelector(s);
function fmtH(v,d=2){return Number(v||0).toLocaleString('vi-VN',{maximumFractionDigits:d})}
function clampH(v,a,b){return Math.max(a,Math.min(b,v))}
async function jsonH(url,options={},timeout=45000){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...options,signal:ctl.signal,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}finally{clearTimeout(timer)}}
function estimatePvH(ghi,temp,kwp){const irr=clampH(Number(ghi||0)/1000,0,1.25);const tempPenalty=Number(temp)>25?clampH(1-(Number(temp)-25)*.004,.82,1):1;return Math.round(kwp*irr*.82*tempPenalty*1000)/1000}
async function weatherFor(sys){const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',sys.lat);u.searchParams.set('longitude',sys.lon);u.searchParams.set('forecast_days','2');u.searchParams.set('timezone','auto');u.searchParams.set('current','temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_10m');u.searchParams.set('hourly','temperature_2m,relative_humidity_2m,shortwave_radiation,diffuse_radiation,wind_speed_10m');const r=await fetch(u);if(!r.ok)throw new Error(`Open-Meteo HTTP ${r.status}`);const d=await r.json();const h=d.hourly||{};return{source:'Open-Meteo direct',timezone:d.timezone,current:d.current||{},time:h.time||[],temperature:h.temperature_2m||[],humidity:h.relative_humidity_2m||[],ghi:h.shortwave_radiation||[],diffuse:h.diffuse_radiation||[],wind:h.wind_speed_10m||[]}}
function startIndex(times,current){const key=String(current||'').slice(0,13);let i=times.findIndex(t=>String(t).slice(0,13)===key);if(i<0)i=times.findIndex(t=>String(t).slice(0,13)>key);return i<0?0:i}
async function buildRun(){const sys=EnergyGuardAuth.loadSystem();const status=$h('#run-status');status.textContent=`Đang chạy forecast cho ${sys.name}…`;status.className='status';const w=await weatherFor(sys);const start=startIndex(w.time,w.current?.time);const labels=w.time.slice(start,start+24);const rows=labels.map((t,i)=>{const j=start+i;return{hour:Number(String(t).slice(11,13)),weekday:new Date(String(t).slice(0,10)+'T12:00:00').getDay(),month:Number(String(t).slice(5,7)),temperatureC:w.temperature[j],humidityPct:w.humidity[j],windSpeedKmh:w.wind[j],ghiWm2:w.ghi[j],diffuseWm2:w.diffuse[j]}});let loadResp;let fallback=false;try{loadResp=await jsonH(ML_BASE_HISTORY+'/predict',{method:'POST',body:JSON.stringify({baseLoadKw:Number(sys.dailyConsumptionKwh||20)/24,hours:rows})})}catch{fallback=true;loadResp=await jsonH(API_BASE_HISTORY+'/api/predict/load',{method:'POST',body:JSON.stringify({baseLoadKw:Number(sys.dailyConsumptionKwh||20)/24,hours:rows})})}const load=(loadResp.forecast||[]).map(x=>Number(x.predictedLoadKw||0));const solar=rows.map(r=>estimatePvH(r.ghiWm2,r.temperatureC,Number(sys.solarKwp||0)));const opt=await jsonH(API_BASE_HISTORY+'/api/optimize/bess',{method:'POST',body:JSON.stringify({solarKw:solar,loadKw:load,batteryCapacityKwh:Number(sys.batteryKwh||0),initialSocPct:Number(sys.initialSocPct||60),minSocPct:15,maxSocPct:95,maxChargeKw:Math.min(5,Number(sys.batteryKwh||0)),maxDischargeKw:Math.min(5,Number(sys.batteryKwh||0)),roundTripEfficiency:.9})});const s=opt.summary||{};const run={id:crypto.randomUUID?crypto.randomUUID():`run-${Date.now()}`,systemId:sys.id,systemName:sys.name,modelName:loadResp.algorithm||loadResp.model||(fallback?'transparent-baseline-v1':'trained-ml'),modelVersion:loadResp.model||null,weatherSource:w.source,forecastStartedAt:labels[0]||new Date().toISOString(),horizonHours:24,summary:{solarKwh:Number(s.solarKwh??solar.reduce((a,b)=>a+b,0)),loadKwh:load.reduce((a,b)=>a+b,0),gridImportKwh:Number(s.gridImportKwh||0),gridExportKwh:Number(s.gridExportKwh||0),batteryChargeKwh:Number(s.batteryChargeKwh||0),batteryDischargeKwh:Number(s.batteryDischargeKwh||0),finalSocPct:Number(s.finalSocPct||0),solarCoveragePct:Number(s.solarCoveragePct||0)},createdAt:new Date().toISOString()};await EnergyGuardAuth.pushForecastRun(run);status.textContent=`Đã lưu forecast ${run.modelName} cho ${sys.name}.`;status.className='status ok';await renderHistory()}
function renderRun(run){const s=run.summary||{};const card=document.createElement('article');card.className='run-card';card.innerHTML=`<div class="run-title"><strong>${run.systemName||'Hệ thống'}</strong><small>${new Date(run.createdAt||run.forecastStartedAt).toLocaleString('vi-VN')} · ${run.modelName||'—'}</small></div><div class="run-metric"><small>Solar</small><strong>${fmtH(s.solarKwh)} kWh</strong></div><div class="run-metric"><small>Grid import</small><strong>${fmtH(s.gridImportKwh)} kWh</strong></div><div class="run-metric"><small>Coverage</small><strong>${fmtH(s.solarCoveragePct,1)}%</strong></div><div class="run-metric"><small>Final SOC</small><strong>${fmtH(s.finalSocPct,1)}%</strong></div>`;return card}
async function renderHistory(){const sys=EnergyGuardAuth.loadSystem();$h('#history-sub').textContent=`Hệ thống đang chọn: ${sys.name} · ${sys.solarKwp} kWp solar · ${sys.batteryKwh} kWh battery`;const out=await EnergyGuardAuth.getForecastHistory();const runs=(out.runs||[]).filter(r=>!r.systemId||r.systemId===sys.id);$h('#storage-pill').textContent=out.persistent?'PostgreSQL persistence':'Local fallback / server-memory';$h('#stat-runs').textContent=runs.length;const avg=(key)=>runs.length?runs.reduce((a,r)=>a+Number(r.summary?.[key]||0),0)/runs.length:0;$h('#stat-grid').textContent=`${fmtH(avg('gridImportKwh'))} kWh`;$h('#stat-coverage').textContent=`${fmtH(avg('solarCoveragePct'),1)}%`;$h('#stat-model').textContent=runs[0]?.modelName||'—';const list=$h('#history-list');list.innerHTML='';if(!runs.length){list.innerHTML='<div class="status">Chưa có forecast nào cho hệ thống này. Bấm “Ghi forecast mới”.</div>';return}runs.forEach(r=>list.appendChild(renderRun(r))}
$h('#record-run')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;const old=b.textContent;b.textContent='Đang chạy…';try{await buildRun()}catch(err){const st=$h('#run-status');st.textContent='Không thể ghi forecast: '+err.message;st.className='status warn'}finally{b.disabled=false;b.textContent=old}});
$h('#clear-history')?.addEventListener('click',()=>{EnergyGuardAuth.clearLocalHistory();renderHistory()});
renderHistory();
